### ISSUE TITLE
certbund-contact, dev-rework-notification: travis build fails

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq#21]
Right now travis-builds fail on ou our branches certbund-contact, dev-rework-notification and integrated. 

When we are close to master with dev-docstrings the travis build succeeds: https://travis-ci.org/Intevation/intelmq/builds/208956737

So our changes are causing the trouble. Analysing the latest fail: https://travis-ci.org/Intevation/intelmq/builds/209490444
checking python3.4, we have two commands failing:

* `The command "INTELMQ_TEST_DATABASES=1 nosetests --with-coverage --cover-package=intelmq" exited with 1.`
* `The command "pep8 intelmq/{bots,lib,bin}" exited with 1.`

## nosetest fails
```
Ran 380 tests in 22.331s
FAILED (errors=2, failures=1)
```

```
ERROR: Build an empty event with contact info derived from contact_descriptions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.4/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: build_test_event() missing 2 required positional arguments: 'contact_descriptions' and 'section'
``` 
probably caused by `./intelmq/tests/bots/experts/certbund_contact/test_rules.py:def build_test_event` 
my idea is that the code seaching for tests finds that function because of the name.

```
  File "/home/travis/build/Intevation/intelmq/intelmq/bots/experts/certbund_contact/ruleexpert.py", line 3, in <module>
    from intelmqmail.script import load_scripts
ImportError: No module named 'intelmqmail'
```
there is no intelmqmail installed, the test should be changed to check and skip if the module is not found.

```
FAIL: test_ipv4_lookup (intelmq.tests.bots.experts.ripencc_abuse_contact.test_expert.TestRIPENCCExpertBot)
```
this is an upstream problem and fixed in 
https://github.com/certtools/intelmq/commit/6792e41716a8d7137039bc1e72d79d65adbc7e84
which will be dragged with a more recent master.

## pep8 fails
about 72 formatting issues.

```
$ pep8 intelmq/{bots,lib,bin}
intelmq/bots/experts/certbund_contact/annotations.py:40:1: E303 too many blank lines (3)
intelmq/bots/experts/certbund_contact/annotations.py:90:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/check-ripe.py:12:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/check-ripe.py:27:6: E225 missing whitespace around operator
intelmq/bots/experts/certbund_contact/check-ripe.py:40:32: E225 missing whitespace around operator
intelmq/bots/experts/certbund_contact/common.py:222:25: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/common.py:223:25: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/expert.py:9:6: E126 continuation line over-indented for hanging indent
intelmq/bots/experts/certbund_contact/expert.py:61:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:31:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:37:9: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:41:13: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:46:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:51:13: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:57:17: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:73:17: E126 continuation line over-indented for hanging indent
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:117:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:129:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/manual-contacts-from-file.py:135:29: E127 continuation line over-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:21:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_data.py:23:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:24:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:28:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_data.py:30:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:31:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:32:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:34:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:35:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:37:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:38:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:40:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:41:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:43:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:44:21: E128 continuation line under-indented for visual indent
intelmq/bots/experts/certbund_contact/ripe_data.py:46:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_data.py:52:5: E266 too many leading '#' for block comment
intelmq/bots/experts/certbund_contact/ripe_data.py:66:5: E266 too many leading '#' for block comment
intelmq/bots/experts/certbund_contact/ripe_data.py:84:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/ripe_data.py:86:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_data.py:105:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_data.py:137:5: E129 visually indented line with same indent as next logical line
intelmq/bots/experts/certbund_contact/ripe_data.py:137:13: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/ripe_data.py:150:24: E261 at least two spaces before inline comment
intelmq/bots/experts/certbund_contact/ripe_diff.py:18:1: E303 too many blank lines (4)
intelmq/bots/experts/certbund_contact/ripe_diff.py:109:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_diff.py:112:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_diff.py:133:1: E302 expected 2 blank lines, found 1
intelmq/bots/experts/certbund_contact/ripe_diff.py:186:11: E126 continuation line over-indented for hanging indent
intelmq/bots/experts/certbund_contact/ripe_import.py:40:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/ripe_import.py:48:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/ripe_import.py:55:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/ripe_import.py:73:62: E202 whitespace before ')'
intelmq/bots/experts/certbund_contact/ripe_import.py:126:64: W291 trailing whitespace
intelmq/bots/experts/certbund_contact/ripe_import.py:128:43: E225 missing whitespace around operator
intelmq/bots/experts/certbund_contact/ripe_import.py:144:9: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/rulesupport.py:6:6: E126 continuation line over-indented for hanging indent
intelmq/bots/experts/certbund_contact/rulesupport.py:31:5: E303 too many blank lines (3)
intelmq/bots/experts/certbund_contact/rulesupport.py:68:32: E225 missing whitespace around operator
intelmq/bots/experts/certbund_contact/rulesupport.py:126:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:127:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:128:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:129:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:152:1: E303 too many blank lines (4)
intelmq/bots/experts/certbund_contact/rulesupport.py:240:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:241:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:242:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:243:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:244:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:245:17: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/rulesupport.py:287:5: E303 too many blank lines (2)
intelmq/bots/experts/certbund_contact/rulesupport.py:361:15: E127 continuation line over-indented for visual indent
intelmq/bots/experts/certbund_contact/rulesupport.py:409:1: E303 too many blank lines (3)
intelmq/bots/experts/certbund_contact/rulesupport.py:411:34: E203 whitespace before ':'
intelmq/bots/experts/certbund_contact/rulesupport.py:424:13: W503 line break before binary operator
intelmq/bots/experts/certbund_contact/example-rules/05inhibitions.py:5:6: E126 continuation line over-indented for hanging indent
intelmq/bots/experts/certbund_contact/example-rules/20prioritize_contacts.py:5:6: E126 continuation line over-indented for hanging indent
intelmq/bots/experts/certbund_contact/example-rules/50shadowserver.py:52:5: E123 closing bracket does not match indentation of 
```

**Comment by bernhardreiter** [comment]
9eddf413302ba2edf25142bdd5cc686310dad964 reduces the nose fails to
`FAILED (SKIP=1, failures=1)` which is the one from upstream.

And removes two pep8 warnings.

**Comment by bernhardreiter** [comment]
75bc299fd70b86d9d8da42df58763edf69070575 should have no pep8 issues anymore.

**Comment by bernhardreiter** [comment]
We should move to the latest version of http://pycodestyle.pycqa.org (which ignores W503 in the default configuration). I'm preparing a pull-request for certtools/intelmq

**Comment by bernhardreiter** [comment]
Started https://github.com/Intevation/intelmq/tree/dev-move-to-pycodestyle but the current pycodestyle will also find other issues. :)

**Comment by wagner-certat** [comment]
We can ignore W503, that's fine

**Comment by bernhardreiter** [comment]
Since a1ab08fad043925a5ff8950825637c0d585f42c3 certbund-contact branch build is green again.
(The last build had one external network failure.)
