### ISSUE TITLE
ripe import for cb database fails on some abuse_c handles

### ISSUE THREAD

**Issue by wagner-certat** [Intevation/intelmq#33]
With the AT data we get this error

```
** Loaded 622 entries from delegated file delegated-ripencc-latest
Traceback (most recent call last):
  File "/home/cp-server/fody_importer/intelmq/intelmq/bots/experts/certbund_contact/ripe_diff.py", line 267, in <module>
    main()
  File "/home/cp-server/fody_importer/intelmq/intelmq/bots/experts/certbund_contact/ripe_diff.py", line 255, in main
    inet6num_list) = ripe_data.load_ripe_files(options)
  File "/home/cp-server/fody_importer/intelmq/intelmq/bots/experts/certbund_contact/ripe_data.py", line 136, in load_ripe_files
    role_index, verbose=options.verbose)
  File "/home/cp-server/fody_importer/intelmq/intelmq/bots/experts/certbund_contact/ripe_data.py", line 486, in sanitize_split_and_modify
    obj_list_a, organisation_list, organisation_index, role_index, verbose)
  File "/home/cp-server/fody_importer/intelmq/intelmq/bots/experts/certbund_contact/ripe_data.py", line 398, in modify_for_abusec
    role = role_index[abuse_c]
KeyError: 'CIAC5-RIPE'
```
Previously this happened only for one handle, now for these (with the AT country restriction):
```
'IOAA1-RIPE', 'HFCR1-RIPE', 'WOCA1-RIPE', 'DSAC6-RIPE', 'AACR14-RIPE', 'TACR5-RIPE', 'TACR5-RIPE', 'LACR19-RIPE', 'SKCR1-RIPE', 'HACR25-RIPE', 'MOAC2-RIPE', 'GTAC3-RIPE', 'WCAC1-RIPE', 'HPOS1-RIPE', 'GNAC5-RIPE', 'AVCR2-RIPE', 'HAAC4-RIPE', 'COSA2-RIPE', 'FTAC3-RIPE', 'SACR87-RIPE', 'SACR88-RIPE', 'GRED1-RIPE', 'KOAC3-RIPE', 'UIAC2-RIPE', 'MAAC10-RIPE', 'SACR89-RIPE', 'NACR2-RIPE', 'AACR14-RIPE', 'AACR14-RIPE', 'DACR18-RIPE', 'KACR35-RIPE', 'NACR2-RIPE', 'NACR2-RIPE', 'SBSC2-RIPE', 'JGVA3-RIPE', 'FUAC2-RIPE', 'BTOE1-RIPE', 'KKCR2-RIPE', 'KACR36-RIPE', 'TMVA2-RIPE', 'CEAC1-RIPE', 'LVSC2-RIPE', 'CEAC1-RIPE', 'SACR92-RIPE', 'OACR11-RIPE', 'FGAC1-RIPE', 'RACR24-RIPE', 'NFAS4-RIPE', 'LMAC14-RIPE', 'TBAC8-RIPE', 'WNAC2-RIPE', 'KIAA1-RIPE', 'JAAC3-RIPE', 'BVCR1-RIPE', 'WACR6-RIPE', 'HLAC5-RIPE', 'ASDA5-RIPE', 'CNAC2-RIPE', 'CNAC2-RIPE', 'CNAC2-RIPE', 'LMAC14-RIPE', 'PTAC5-RIPE', 'FSAC9-RIPE', 'ASDA6-RIPE', 'BLBC1-RIPE', 'ETAC2-RIPE', 'CEAC1-RIPE', 'NACR31-RIPE', 'FTAC6-RIPE', 'AACR14-RIPE', 'WMAC5-RIPE', 'WMAC5-RIPE', 'ASAC14-RIPE', 'SOFA1-RIPE', 'FBAC11-RIPE', 'HDAC1-RIPE', 'MAAC3-RIPE', 'NACR2-RIPE', 'NACR2-RIPE', 'ADLA4-RIPE', 'VFCR2-RIPE', 'FACR21-RIPE', 'CEAC1-RIPE', 'CEAC1-RIPE', 'BSPC1-RIPE', 'BEAC16-RIPE', 'DNBO1-RIPE', 'SACR97-RIPE', 'DODA3-RIPE', 'DFAC3-RIPE', 'DFAC3-RIPE', 'BOGA2-RIPE', 'LEAC3-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'SGCR2-RIPE', 'BFAC6-RIPE', 'BSCR4-RIPE', 'ABAC17-RIPE', 'EACR25-RIPE', 'NGAC7-RIPE', 'IOAC1-RIPE', 'RIAC3-RIPE', 'DODA3-RIPE', 'EACR19-RIPE', 'ACR38-RIPE', 'WMAC5-RIPE', 'KOSA2-RIPE', 'KOSA2-RIPE', 'FROE1-RIPE', 'CEAC1-RIPE', 'JAAC3-RIPE', 'JAAC3-RIPE', 'WACR3-RIPE', 'NIAC1-RIPE', 'LSAC4-RIPE', 'MSAA7-RIPE', 'LMAC14-RIPE', 'ACR43-RIPE', 'ACR43-RIPE', 'NSCR2-RIPE', 'NACR22-RIPE', 'IOAA1-RIPE', 'GOGE2-RIPE', 'BTTA2-RIPE', 'HDAC1-RIPE', 'TKAC2-RIPE', 'HKCR3-RIPE', 'FOHB1-RIPE', 'SSSC1-RIPE', 'OOAC3-RIPE', 'FBAC12-RIPE', 'UMAC1-RIPE', 'BMAC10-RIPE', 'VIAC3-RIPE', 'JDAC5-RIPE', 'TMOM1-RIPE', 'PFAC3-RIPE', 'SFAC3-RIPE', 'TKAC2-RIPE', 'CMAC9-RIPE', 'FTAC7-RIPE', 'FNAC6-RIPE', 'BACR44-RIPE', 'UMAC1-RIPE', 'SRDC1-RIPE', 'SRDC1-RIPE', 'GNAC5-RIPE', 'GNAC5-RIPE', 'FACR41-RIPE', 'FACR41-RIPE', 'FACR41-RIPE', 'TFAC4-RIPE', 'LMAC14-RIPE', 'PSOM2-RIPE', 'NVOA1-RIPE', 'BHAC5-RIPE', 'OBAC1-RIPE', 'NORA1-RIPE', 'SSAC20-RIPE', 'HFBA1-RIPE', 'FDAC3-RIPE', 'FBAC12-RIPE', 'SRBS2-RIPE', 'EECR1-RIPE', 'FAAC8-RIPE', 'OPFA1-RIPE', 'TFAC6-RIPE', 'JACR15-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'AACR46-RIPE', 'LVSC2-RIPE', 'ISOB1-RIPE', 'RPAC4-RIPE', 'PACR30-RIPE', 'TBAC10-RIPE', 'JBAC2-RIPE', 'EACR28-RIPE', 'BHAC6-RIPE', 'MIAC2-RIPE', 'MIAC2-RIPE', 'SACR109-RIPE', 'SACR109-RIPE', 'BRAC15-RIPE', 'BRAC15-RIPE', 'VACR33-RIPE', 'NGNA1-RIPE', 'STAC17-RIPE', 'HNAC6-RIPE', 'SIAC10-RIPE', 'SIAC10-RIPE', 'SIAC10-RIPE', 'NACR40-RIPE', 'HACR29-RIPE', 'NFAC8-RIPE', 'WACR12-RIPE', 'IACR10-RIPE', 'DBAC6-RIPE', 'RACR21-RIPE', 'AOCA1-RIPE', 'HIAC1-RIPE', 'HIAC1-RIPE', 'AHKA1-RIPE', 'DODA3-RIPE', 'GACR21-RIPE', 'HIMC1-RIPE', 'SLCR2-RIPE', 'AIAC8-RIPE', 'GACR23-RIPE', 'BFAA1-RIPE', 'MKRA3-RIPE', 'SBAA2-RIPE', 'MFAC5-RIPE', 'SACR87-RIPE', 'SACR87-RIPE', 'IAAC4-RIPE', 'IAAC4-RIPE', 'SACR88-RIPE', 'SACR88-RIPE', 'GRED1-RIPE', 'GRED1-RIPE', 'KOAC3-RIPE', 'KOAC3-RIPE', 'UIAC2-RIPE', 'UIAC2-RIPE', 'MAAC10-RIPE', 'MAAC10-RIPE', 'SACR89-RIPE', 'SACR89-RIPE', 'DACR18-RIPE', 'DACR18-RIPE', 'KACR35-RIPE', 'KACR35-RIPE', 'NACR2-RIPE', 'NACR2-RIPE', 'NACR2-RIPE', 'SBSC2-RIPE', 'SBSC2-RIPE', 'JGVA3-RIPE', 'JGVA3-RIPE', 'FUAC2-RIPE', 'FUAC2-RIPE', 'BTOE1-RIPE', 'BTOE1-RIPE', 'KKCR2-RIPE', 'KKCR2-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'TMVA2-RIPE', 'TMVA2-RIPE', 'CEAC1-RIPE', 'CEAC1-RIPE', 'LVSC2-RIPE', 'LVSC2-RIPE', 'CEAC1-RIPE', 'CEAC1-RIPE', 'SACR92-RIPE', 'SACR92-RIPE', 'OACR11-RIPE', 'OACR11-RIPE', 'FGAC1-RIPE', 'FGAC1-RIPE', 'RACR24-RIPE', 'RACR24-RIPE', 'NFAS4-RIPE', 'NFAS4-RIPE', 'LMAC14-RIPE', 'LMAC14-RIPE', 'TBAC8-RIPE', 'TBAC8-RIPE', 'WNAC2-RIPE', 'WNAC2-RIPE', 'KIAA1-RIPE', 'KIAA1-RIPE', 'BVCR1-RIPE', 'BVCR1-RIPE', 'WACR6-RIPE', 'WACR6-RIPE', 'HLAC5-RIPE', 'HLAC5-RIPE', 'ASDA5-RIPE', 'ASDA5-RIPE', 'CNAC2-RIPE', 'CNAC2-RIPE', 'PTAC5-RIPE', 'PTAC5-RIPE', 'FSAC9-RIPE', 'FSAC9-RIPE', 'ASDA6-RIPE', 'ASDA6-RIPE', 'BLBC1-RIPE', 'BLBC1-RIPE', 'ETAC2-RIPE', 'ETAC2-RIPE', 'CEAC1-RIPE', 'CEAC1-RIPE', 'NACR31-RIPE', 'NACR31-RIPE', 'FTAC6-RIPE', 'FTAC6-RIPE', 'AACR14-RIPE', 'AACR14-RIPE', 'WMAC5-RIPE', 'WMAC5-RIPE', 'WMAC5-RIPE', 'WMAC5-RIPE', 'ASAC14-RIPE', 'FACR40-RIPE', 'SOFA1-RIPE', 'SOFA1-RIPE', 'FBAC11-RIPE', 'FBAC11-RIPE', 'HDAC1-RIPE', 'HDAC1-RIPE', 'MAAC3-RIPE', 'MAAC3-RIPE', 'ADLA4-RIPE', 'ADLA4-RIPE', 'BSPC1-RIPE', 'BSPC1-RIPE', 'BEAC16-RIPE', 'BEAC16-RIPE', 'FTAC7-RIPE', 'DNBO1-RIPE', 'DNBO1-RIPE', 'SACR97-RIPE', 'SACR97-RIPE', 'DODA3-RIPE', 'DODA3-RIPE', 'DFAC3-RIPE', 'DFAC3-RIPE', 'DFAC3-RIPE', 'DFAC3-RIPE', 'BOGA2-RIPE', 'BOGA2-RIPE', 'LEAC3-RIPE', 'LEAC3-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'KACR36-RIPE', 'SGCR2-RIPE', 'SGCR2-RIPE', 'BFAC6-RIPE', 'BFAC6-RIPE', 'BSCR4-RIPE', 'BSCR4-RIPE', 'ABAC17-RIPE', 'ABAC17-RIPE', 'EACR25-RIPE', 'EACR25-RIPE', 'NGAC7-RIPE', 'NGAC7-RIPE', 'IOAC1-RIPE', 'IOAC1-RIPE', 'RIAC3-RIPE', 'RIAC3-RIPE', 'DODA3-RIPE', 'DODA3-RIPE', 'EACR19-RIPE', 'EACR19-RIPE', 'WMAC5-RIPE', 'WMAC5-RIPE', 'ACR38-RIPE', 'ACR38-RIPE', 'FROE1-RIPE', 'CEAC1-RIPE', 'CEAC1-RIPE', 'JAAC3-RIPE', 'JAAC3-RIPE', 'NIAC1-RIPE', 'NIAC1-RIPE', 'LSAC4-RIPE', 'LSAC4-RIPE', 'MSAA7-RIPE', 'MSAA7-RIPE', 'ACR43-RIPE', 'ACR43-RIPE', 'NACR22-RIPE', 'NACR22-RIPE', 'IOAA1-RIPE', 'IOAA1-RIPE', 'GOGE2-RIPE', 'GOGE2-RIPE', 'BTTA2-RIPE', 'BTTA2-RIPE', 'HDAC1-RIPE', 'HDAC1-RIPE', 'HKCR3-RIPE', 'HKCR3-RIPE', 'FOHB1-RIPE', 'FOHB1-RIPE', 'SSSC1-RIPE', 'SSSC1-RIPE', 'OOAC3-RIPE', 'OOAC3-RIPE', 'FBAC12-RIPE', 'FBAC12-RIPE', 'UMAC1-RIPE', 'UMAC1-RIPE', 'BMAC10-RIPE', 'BMAC10-RIPE', 'VIAC3-RIPE', 'VIAC3-RIPE', 'JDAC5-RIPE', 'JDAC5-RIPE', 'TMOM1-RIPE', 'TMOM1-RIPE', 'PFAC3-RIPE', 'PFAC3-RIPE', 'SFAC3-RIPE', 'SFAC3-RIPE', 'TKAC2-RIPE', 'TKAC2-RIPE', 'FTAC7-RIPE', 'BACR44-RIPE', 'BACR44-RIPE', 'UMAC1-RIPE', 'UMAC1-RIPE', 'SRDC1-RIPE', 'SRDC1-RIPE', 'GNAC5-RIPE', 'GNAC5-RIPE', 'TFAC4-RIPE', 'TFAC4-RIPE', 'LMAC14-RIPE', 'LMAC14-RIPE', 'PSOM2-RIPE', 'PSOM2-RIPE', 'NVOA1-RIPE', 'NVOA1-RIPE', 'BHAC5-RIPE', 'BHAC5-RIPE', 'OBAC1-RIPE', 'OBAC1-RIPE', 'NORA1-RIPE', 'NORA1-RIPE', 'SSAC20-RIPE', 'SSAC20-RIPE', 'HFBA1-RIPE', 'HFBA1-RIPE', 'FDAC3-RIPE', 'FDAC3-RIPE', 'FBAC12-RIPE', 'FBAC12-RIPE', 'HBOR1-RIPE', 'HBOR1-RIPE', 'SRBS2-RIPE', 'SRBS2-RIPE', 'EECR1-RIPE', 'EECR1-RIPE', 'FAAC8-RIPE', 'FAAC8-RIPE', 'TFAC6-RIPE', 'TFAC6-RIPE', 'JACR15-RIPE', 'JACR15-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'SMAC5-RIPE', 'AACR46-RIPE', 'AACR46-RIPE', 'ADSA7-RIPE', 'ISOB1-RIPE', 'ISOB1-RIPE', 'RPAC4-RIPE', 'RPAC4-RIPE', 'PACR30-RIPE', 'PACR30-RIPE', 'TBAC10-RIPE', 'TBAC10-RIPE', 'JBAC2-RIPE', 'JBAC2-RIPE', 'EACR28-RIPE', 'EACR28-RIPE', 'BHAC6-RIPE', 'BHAC6-RIPE', 'MIAC2-RIPE', 'MIAC2-RIPE', 'MIAC2-RIPE', 'MIAC2-RIPE', 'SACR109-RIPE', 'SACR109-RIPE', 'BRAC15-RIPE', 'BRAC15-RIPE', 'VACR33-RIPE', 'VACR33-RIPE', 'NGNA1-RIPE', 'NGNA1-RIPE', 'STAC17-RIPE', 'STAC17-RIPE', 'HNAC6-RIPE', 'HNAC6-RIPE', 'SIAC10-RIPE', 'SIAC10-RIPE', 'SIAC10-RIPE', 'SIAC10-RIPE', 'HACR29-RIPE', 'HACR29-RIPE', 'NFAC8-RIPE', 'NFAC8-RIPE', 'WACR12-RIPE', 'WACR12-RIPE', 'IACR10-RIPE', 'IACR10-RIPE', 'DBAC6-RIPE', 'DBAC6-RIPE', 'RACR21-RIPE', 'RACR21-RIPE', 'AOCA1-RIPE', 'AOCA1-RIPE', 'HIAC1-RIPE', 'HIAC1-RIPE', 'AHKA1-RIPE', 'AHKA1-RIPE', 'DODA3-RIPE', 'DODA3-RIPE', 'GACR21-RIPE', 'GACR21-RIPE', 'SLCR2-RIPE', 'SLCR2-RIPE', 'AIAC8-RIPE', 'AIAC8-RIPE', 'GACR23-RIPE', 'GACR23-RIPE', 'BFAA1-RIPE', 'BFAA1-RIPE', 'MKRA3-RIPE', 'MKRA3-RIPE', 'SBAA2-RIPE', 'SBAA2-RIPE', 'MFAC5-RIPE', 'MFAC5-RIPE'
```

**Comment by bernhardreiter** [comment]
@wagner-certat thanks for asking!

Which version are you using precisely (best is to write the git version)?
(There used to be some problems because the RIPE database has changed,
it may make sense to use the latest version from the repo.)

@bernhard-herzog can you peek a look, once the version is known?

**Comment by wagner-certat** [comment]
We are on the branch certbund-contact, `git describe` gives `1.0.0.dev5-999-g3f9eb71` with the latest commit being 3f9eb71aff966c7510d281658c1242eb168a0e3f
We will also further investigate this error.

**Comment by bernhard-herzog** [comment]
With the switch to IntelMQ 1.1, we've split the code from the `certbund-contact` branch into a separate repository: https://github.com/Intevation/intelmq-certbund-contact

The RIPE importer from there has some fixes, including one that addresses this exact problem. The last commit for that was https://github.com/Intevation/intelmq-certbund-contact/commit/92f6484354a1b463756bcc71b8212db3ddc3f1d5

**Comment by wagner-certat** [comment]
Oh. I missed this change.

I have linked this now also in the Ecosystem document:
https://github.com/certtools/intelmq/blob/develop/docs/Ecosystem.md#intelmq-fody--backend
